function maqmexogui

fMain = figure( ...
    'Name', 'Maq/Mexo UI', ...
    'Visible', 'off', ...
    'Position', [0 0 400 100], ...
    'MenuBar', 'none', ...
    'NumberTitle', 'off');

hMexoMenu = uimenu('Label', 'Texo');
uimenu(hMexoMenu, ...
    'Label', 'Initialize', ...
    'Callback', {@MexoInitCallback});

hTriggers = uimenu(hMexoMenu, ...
    'Label', 'Triggers', ...
    'Separator', 'On');

hInput1 = uimenu(hTriggers, 'Label', 'Input1');
uimenu(hInput1, ...
    'Label', 'None', ...
    'Callback', {@MexoInput1NoneCallback});
uimenu(hInput1, ...
    'Label', 'Line', ...
    'Callback', {@MexoInput1LineCallback});
uimenu(hInput1, ...
    'Label', 'Frame', ...
    'Callback', {@MexoInput1FrameCallback});

hOutput1 = uimenu(hTriggers, 'Label', 'Output1');
uimenu(hOutput1, ...
    'Label', 'None', ...
    'Callback', {@MexoOutput1NoneCallback});
uimenu(hOutput1, ...
    'Label', 'Line', ...
    'Callback', {@MexoOutput1LineCallback});
uimenu(hOutput1, ...
    'Label', 'Frame', ...
    'Callback', {@MexoOutput1FrameCallback});
uimenu(hOutput1, ...
    'Label', 'Clock', ...
    'Callback', {@MexoOutput1ClockCallback});

hOutput2 = uimenu(hTriggers, 'Label', 'Output2');
uimenu(hOutput2, ...
    'Label', 'None', ...
    'Callback', {@MexoOutput2NoneCallback});
uimenu(hOutput2, ...
    'Label', 'Line', ...
    'Callback', {@MexoOutput2LineCallback});
uimenu(hOutput2, ...
    'Label', 'Frame', ...
    'Callback', {@MexoOutput2FrameCallback});
uimenu(hOutput2, ...
    'Label', 'Clock', ...
    'Callback', {@MexoOutput2ClockCallback});

uimenu(hMexoMenu, ...
    'Label','Parameters', ...
    'Callback', {@MexoSetParamsCallback});

hMaqMenu = uimenu('Label', 'DAQ');
uimenu(hMaqMenu,...
    'Label', 'Initialize', ...
    'Callback', {@MaqInitCallback});
uimenu(hMaqMenu, ...
    'Label', 'Run', ...
    'Callback', {@MaqRunCallback});
uimenu(hMaqMenu, ...
    'Label', 'Stop', ...
    'Enable', 'Off', ...
    'Callback', {@MaqStopCallback});
uimenu(hMaqMenu, ...
    'Label', 'Ext Trigger', ...
    'Separator', 'On', ...
    'Callback', {@MaqExtTriggerCallback});
uimenu(hMaqMenu, ...
    'Label','Ext Clock', ...
    'Callback', {@MaqExtClockCallback});
uimenu(hMaqMenu, ...
    'Label','Parameters', ...
    'Callback', {@MaqSetParamsCallback});

hStatusText = uicontrol(fMain, ...
    'Style', 'text', ...
    'String', 'Current status information', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0 0 400 18]);

movegui(fMain,'center');
set(fMain,'Visible','on');

end