function maqmexogui

fMain = figure( ...
    'Name', 'Maq/Mexo UI', ...
    'Visible', 'off', ...
    'Position', [0 0 400 100], ...
    'MenuBar', 'none', ...
    'NumberTitle', 'off');

hMexoMenu = uimenu('Label', 'Texo');
uimenu(hMexoMenu, ...
    'Label', 'Initialize', ...
    'Callback', {@MexoInitCallback});

hTriggers = uimenu(hMexoMenu, ...
    'Label', 'Triggers', ...
    'Separator', 'On');

hInput1 = uimenu(hTriggers, 'Label', 'Input1');
uimenu(hInput1, ...
    'Label', 'None', ...
    'Callback', {@MexoInput1NoneCallback});
uimenu(hInput1, ...
    'Label', 'Line', ...
    'Callback', {@MexoInput1LineCallback});
uimenu(hInput1, ...
    'Label', 'Frame', ...
    'Callback', {@MexoInput1FrameCallback});

hOutput1 = uimenu(hTriggers, 'Label', 'Output1');
uimenu(hOutput1, ...
    'Label', 'None', ...
    'Callback', {@MexoOutput1NoneCallback});
uimenu(hOutput1, ...
    'Label', 'Line', ...
    'Callback', {@MexoOutput1LineCallback});
uimenu(hOutput1, ...
    'Label', 'Frame', ...
    'Callback', {@MexoOutput1FrameCallback});
uimenu(hOutput1, ...
    'Label', 'Clock', ...
    'Callback', {@MexoOutput1ClockCallback});

hOutput2 = uimenu(hTriggers, 'Label', 'Output2');
uimenu(hOutput2, ...
    'Label', 'None', ...
    'Callback', {@MexoOutput2NoneCallback});
uimenu(hOutput2, ...
    'Label', 'Line', ...
    'Callback', {@MexoOutput2LineCallback});
uimenu(hOutput2, ...
    'Label', 'Frame', ...
    'Callback', {@MexoOutput2FrameCallback});
uimenu(hOutput2, ...
    'Label', 'Clock', ...
    'Callback', {@MexoOutput2ClockCallback});

uimenu(hMexoMenu, ...
    'Label','Parameters', ...
    'Callback', {@MexoSetParamsCallback});

hMaqMenu = uimenu('Label', 'DAQ');
uimenu(hMaqMenu,...
    'Label', 'Initialize', ...
    'Callback', {@MaqInitCallback});
uimenu(hMaqMenu, ...
    'Label', 'Run', ...
    'Callback', {@MaqRunCallback});
uimenu(hMaqMenu, ...
    'Label', 'Stop', ...
    'Enable', 'Off', ...
    'Callback', {@MaqStopCallback});
uimenu(hMaqMenu, ...
    'Label', 'Ext Trigger', ...
    'Separator', 'On', ...
    'Callback', {@MaqExtTriggerCallback});
uimenu(hMaqMenu, ...
    'Label','Ext Clock', ...
    'Callback', {@MaqExtClockCallback});
uimenu(hMaqMenu, ...
    'Label','Parameters', ...
    'Callback', {@MaqSetParamsCallback});

hStatusText = uicontrol(fMain, ...
    'Style', 'text', ...
    'String', 'Current status information', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0 0 400 18]);

movegui(fMain, 'center');
set(fMain, 'Visible', 'on');

%tx = texoTransmitParams();
%rx = texoReceiveParams();
%apr = texoCurve();
%info = texoLineInfo();
seqprms = daqSequencePrms();
rlprms = daqRaylinePrms();

seqprms.freeRun = false;
seqprms.hpfBypass = false;
seqprms.divisor = 0;
seqprms.externalTrigger = true;
seqprms.externalClock = true;
seqprms.lnaGain = 1; 
seqprms.pgaGain = 1;
seqprms.biasCurrent = 1;
seqprms.fixedTGC = true;
seqprms.fixedTGCLevel = 40;

rlprms.lineDuration = 70;
rlprms.numSamples = 2678; 
rlprms.gainOffset = 0;
rlprms.gainDelay = 0;
rlprms.rxDelay = 0;
rlprms.channels = [uint32(2^32) uint32(2^32) uint32(2^32) uint32(2^32)];
rlprms.decimation = 0;
rlprms.sampling = 40;

    function prms = GetDaqParams(seq, rl)
        
        if strcmp(class(seq), 'daqSequencePrms') || strcmp(class(rl), 'daqRaylinePrms')
            error('incorrect class type');
        end
        
        prms = [struct2cell(struct(seq)); struct2cell(struct(rl))];
        
        prms([4 5 16]) = [];
    end

    function SetDaqParams(seq, rl, prms)
        
        if strcmp(class(seq), 'daqSequencePrms') || strcmp(class(rl), 'daqRaylinePrms')
            error('incorrect class type');
        end
        
        seq.freeRun = prms(1);
        seq.hpfBypass = prms(2);
        seq.divisor = prms(3);
        seq.lnaGain = prms(4);
        seq.pgaGain = prms(5);
        seq.fixedTGC = prms(6);
        seq.fixedTGCLevel = prms(7);
        
        rl.lineDuration = prms(8);
        rl.numSamples = prms(9);
        rl.gainOffset = prms(10);
        rl.gainDelay = prms(11);
        rl.rxDelay = prms(12);
        rl.decimation = prms(13);
        rl.sampling = prms(14);
    end

    function MexoSetParamsCallback(hObject, eventdata)
        
        fMexoParams = figure( ...
            'Name', 'Mexo Parameters', ...
            'Visible', 'off', ...
            'Position', [0 0 400 400], ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off');
        
        movegui(fMexoParams, 'center');
        set(fMexoParams, 'Visible', 'On');
    end

    function MaqSetParamsCallback(hObject, eventdata)
        
        fMaqParams = figure( ...
            'Name', 'Maq Parameters', ...
            'Visible', 'off', ...
            'Position', [0 0 200 400], ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off');
        cnames = {'value'};
        rnames = {'divisor', 'lnaGain', 'pgaGain', 'biasCurrent'};
        MaqParams = ones(4,1);
        
        uitable(fMaqParams, ...
            'RowName', rnames, ...
            'ColumnName', cnames, ...
            'ColumnEditable', [true], ...
            'ColumnWidth', {'auto'}, ...
            'Data', struct2cell(struct(seqprms)), ...
            'Position', [1 1 200 400]);
        
        
        
        movegui(fMaqParams, 'center');
        set(fMaqParams, 'Visible', 'On');
        
    end

end