%
%
addpath ../simulator/
addpath ../beamformer/

numofchannels = 128;
pitch = 300e-6;
sensorGeom = zeros(numofchannels,3);
sensorGeom(:,1) = ((-numofchannels/2*pitch+pitch/2:pitch:(numofchannels/2)*pitch-pitch/2))';

sourceGeom = [0 0 0.02];

bfmopt = bfmset( ...
    'ArrayPitch', pitch, ...
    'RxCurveBtm', 100, ...
    'RxCurveMid', 68, ...
    'RxCurveTop', 10, ...
    'RxCurveVmid', 52, ...
    'RxCurveDepth', 0.055, ...
    'SampleFreq', 40e6, ...
    'SoundSpeed', 1540, ...
    'Photoacoustic', false ...
    );
    
simopt = simset( ...
    'Amplitude', 1, ...
    'Frequency', 10e6, ...
    'GaussFractBandwidth', 1.2, ...
    'NoiseSnr', 20, ...
    'PulseType', 'Bipolar', ...
    'SampleFreq', 40e6, ...
    'SensorGeom', sensorGeom, ...
    'SoundSpeed', 1540, ...
    'SourceGeom', sourceGeom, ...
    'TimeLength', 1040*25e-9 ...
    );

rfc = simulation(simopt);
%rfc_b = bandpass(rfc,6.6,5.28,40);
%bfm_b = bmbeamform(rfc_b, bfmopt);

clear sensorGeom numofchannels pitch sourceGeom 
