%
%
addpath ../simulator/
addpath ../beamformer/

numofchannels = 128;
pitch = 300e-6;
sensorGeom = zeros(numofchannels,3);
sensorGeom(:,1) = ((-numofchannels/2*pitch+pitch/2:pitch:(numofchannels/2)*pitch-pitch/2))';

z = 0.01:0.01:0.04;
x = -0.015:0.01:0.015;
[X Z] = meshgrid(x,z);

sourceGeom = [reshape(X,16,1) zeros(16,1) reshape(Z,16,1)];

bfmopt = bfmset( ...
    'ArrayPitch', pitch, ...
    'GaussApodization', true, ...
    'GaussWinAlpha', 1.5, ...
    'RxCurveBtm', 128, ...
    'RxCurveMid', 68, ...%68
    'RxCurveTop', 4, ...%4
    'RxCurveVmid', 50, ...
    'SampleFreq', 40e6, ...
    'SoundSpeed', 1482, ...
    'Photoacoustic', true ...
    );

simopt = simset( ...
    'Amplitude', 1, ...
    'Frequency', 6.6e6, ...
    'GaussFractBandwidth', 0.8, ...
    'NoiseSnr', 10, ...
    'PulseType', 'Gaussian', ...
    'SampleFreq', 40e6, ...
    'SensorGeom', sensorGeom, ...
    'SoundSpeed', 1482, ...
    'SourceGeom', sourceGeom, ...
    'TimeLength', 1350*25e-9 ...
    );

rfc = simulation(simopt);
%rfc_b = bandpass(rfc,6.6,5.28,40);
%bfm_b = bmbeamform(rfc_b, bfmopt);

clear sensorGeom numofchannels pitch sourceGeom X Z x z
