%
%
addpath ./simulator/
addpath ./beamformer/

numofchannels = 128;
pitch = 300e-6;
sensorGeom = zeros(numofchannels,3);
sensorGeom(:,1) = ((-numofchannels/2*pitch+pitch/2:pitch:(numofchannels/2)*pitch-pitch/2))';

srcZ = 0.010:0.005:0.060;
srcX1 = ones(11,1).*0.0005;
srcX2 = ones(11,1).*(-0.0005);
sourceGeom = [ srcX1 zeros(11,1) srcZ.';
               srcX2 zeros(11,1) srcZ.'];

simopt = simset( ...
    'Amplitude', 1, ...
    'Frequency', 6.6e6, ...
    'GaussFractBandwidth', 0.8, ...
    'NoiseSnr', 20, ...
    'PulseType', 'Gaussian', ...
    'SampleFreq', 40e6, ...
    'SensorGeom', sensorGeom, ...
    'SoundSpeed', 1540, ...
    'SourceGeom', sourceGeom, ...
    'TimeLength', 1689*25e-9 ...
    );

rfc = simulation(simopt);

clear sensorGeom numofchannels pitch sourceGeom srcZ srcX1 srcX2
